### ISSUE TITLE
Shape-from--Silhouettes and Hole patching

### ISSUE THREAD

**Issue by pengsida** [wuminye/NHR#1]
Could you release the codes about "Shape-from--Silhouettes" and "Hole patching"?

**Comment by wuminye** [comment]
SfS code is released at [shape_from_silhouettes](https://github.com/wuminye/shape_from_silhouettes)

I have uploaded hole_patching code,  which can be found in tools/ folder.

**Comment by pengsida** [comment]
Cool!
Thank you very much.
