### ISSUE TITLE
How to make your own data

### ISSUE THREAD

**Issue by liaohuanxuan** [wuminye/NHR#12]
good job !
Can you provide detailed steps or codes to process the data?
thanks !

**Comment by wuminye** [comment]
We have provided [cameras_from_metashape.py](https://github.com/wuminye/NHR/blob/master/tools/cameras_from_metashape.py)  to convert camera parameters from Metashape format to NHR's parameter format. It's important to note that additional undistortion operations are required for the images

**Comment by liaohuanxuan** [comment]
Thank you for your reply!
Are the pointcloud files also from the metashape?
