### ISSUE TITLE
Broken link for dance data

### ISSUE THREAD

**Issue by isarandi** [wuminye/NHR#13]
Hi, thanks for the dataset! Apparently the dance part is missing, the link gives an error. The links to the other files work.

dance(7z, 8.6GB) https://drive.google.com/file/d/1gtS6C4uCI_YV_AJP6xLn_dGUGhMitL9T/view?usp=sharing

**Comment by AmmonZ** [comment]
same here, will the authors update the link?

**Comment by wuminye** [comment]
I apologize for any inconvenience caused by the expired link. Unfortunately, the link to the dance scene has been inactive for quite some time, and I couldn't find a better way to share the data. Therefore, I've made the decision to remove this scene from the NHR dataset.
