### ISSUE TITLE
ModuleNotFoundError: No module named 'models_lpf'

### ISSUE THREAD

**Issue by OOF-dura** [wuminye/NHR#3]
/NHR/modeling/UNet/unet_parts.py in <module>
      4 import torch.nn as nn
      5 import torch.nn.functional as F
----> 6 import models_lpf
      7 
      8 

ModuleNotFoundError: No module named 'models_lpf'

![image](https://user-images.githubusercontent.com/22954901/108687894-3ac90800-7532-11eb-8782-acbde7b0256b.png)

### ENVs:
Ubuntu16
CUDA10

**Comment by wuminye** [comment]
'models_lpf' module is the old version of 'antialiased-cnns'.

you can find the the old version at https://github.com/adobe/antialiased-cnns/tree/cd65885a4e2de0dcedbb1a4793a6d58f03530e6e.  (where a folder named 'models_lpf')
