### ISSUE TITLE
RuntimeError: expected scalar type Float but found Half

### ISSUE THREAD

**Issue by ghost** [wuminye/NHR#4]
When I ran train_net.py, I got an error

> RuntimeError: expected scalar type Float but found Half (data_ptr<float> at /home/cy/anaconda3/envs/render/lib/python3.6/s                                                                                           ite-packages/torch/include/ATen/core/TensorMethods.h:6321)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f32dc94a627 in /home/cy/anaconda3/envs/NHR                                                                                           /lib/python3.6/site-packages/torch/lib/libc10.so)
> frame #1: float* at::Tensor::data_ptr<float>() const + 0xa60 (0x7f32bbb33480 in /home/cy/anaconda3/envs/NHR/lib/python3.6/                                                                                           site-packages/pointnet2-0.0.0-py3.6-linux-x86_64.egg/pointnet2_cuda.cpython-36m-x86_64-linux-gnu.so)
> frame #2: group_points_wrapper_fast(int, int, int, int, int, at::Tensor, at::Tensor, at::Tensor) + 0x27 (0x7f32bbb34427 in                                                                                            /home/cy/anaconda3/envs/NHR/lib/python3.6/site-packages/pointnet2-0.0.0-py3.6-linux-x86_64.egg/pointnet2_cuda.cpython-36m                                                                                           -x86_64-linux-gnu.so)
> frame #3: <unknown function> + 0x14947 (0x7f32bbb2c947 in /home/cy/anaconda3/envs/NHR/lib/python3.6/site-packages/pointnet                                                                                           2-0.0.0-py3.6-linux-x86_64.egg/pointnet2_cuda.cpython-36m-x86_64-linux-gnu.so)
> frame #4: <unknown function> + 0x11a06 (0x7f32bbb29a06 in /home/cy/anaconda3/envs/NHR/lib/python3.6/site-packages/pointnet                                                                                           2-0.0.0-py3.6-linux-x86_64.egg/pointnet2_cuda.cpython-36m-x86_64-linux-gnu.so)
> <omitting python frames>
> frame #11: THPFunction_apply(_object*, _object*) + 0xa1f (0x7f330e1f6e3f in /home/cy/anaconda3/envs/NHR/lib/python3.6/site                                                                                           -packages/torch/lib/libtorch_python.so)

then I found that the error occurred on the line 40 of pointnet2_modules.py, which is 
`new_features = self.mlps[i](new_features)`.
The type of ‘new_features’ as input variable is 'torch.float32', but the type of output of 'self.mlps' is 'torch.float16'.

**Comment by wuminye** [comment]
This error is usually seen when latest apex module is used.  In our implementation, we use an older version (https://github.com/NVIDIA/apex/tree/088985936518be7e25795a30d8ab33affa9db6ed).   I suggest downloading and recompiling the old one.

An alternative is to turn off the apex.  In such a way, you should remove apex stuffs in train_net.py and  engine/trainer.py.

**Comment by ghost** [comment]
> This error is usually seen when latest apex module is used. In our implementation, we use an older version (https://github.com/NVIDIA/apex/tree/088985936518be7e25795a30d8ab33affa9db6ed). I suggest downloading and recompiling the old one.
> 
> An alternative is to turn off the apex. In such a way, you should remove apex stuffs in train_net.py and engine/trainer.py.

我修改了pointnet2_modules.py的第154行`new_features = self.mlp(new_features).type(torch.float32)`和第40行`new_features = self.mlps[i](new_features).type(torch.float32)`，修改之后可以正常运行，请问这样解决是否合理呢？

**Comment by wuminye** [comment]
> > This error is usually seen when latest apex module is used. In our implementation, we use an older version (https://github.com/NVIDIA/apex/tree/088985936518be7e25795a30d8ab33affa9db6ed). I suggest downloading and recompiling the old one.
> > An alternative is to turn off the apex. In such a way, you should remove apex stuffs in train_net.py and engine/trainer.py.
> 
> 我修改了pointnet2_modules.py的第154行`new_features = self.mlp(new_features).type(torch.float32)`和第40行`new_features = self.mlps[i](new_features).type(torch.float32)`，修改之后可以正常运行，请问这样解决是否合理呢？

Nice try 👍 
I don't think it's an efficient way, but it may work.
