### ISSUE TITLE
Output of Network Fine-tuning

### ISSUE THREAD

**Issue by ghost** [wuminye/NHR#5]
你好！我根据GitHub的readme先运行了train_net.py，将模型训练至第30epoch，紧接着我运行了以下步骤
```
Network Fine-tuning
run cd tools && python finetune.py <gpu id> <path to checkpoint> <the number of resuming epoch>
```
但是我并没有发现这一步有输出，并且这一步很快就结束了，我的终端上只显示了logging的打印内容
```
0 / 200
50 / 200
100 / 200
150 / 200
load 56 Ts, 56 Ks, 200 frame, 33713011 vertices
dataset initialed.
2021-03-18 16:48:28,755 rendering_model.train INFO: Load 1 datasets.
2021-03-18 16:48:30,722 rendering_model.train INFO: Load pretrain model nr_model_30.pth.
```
然后程序执行就结束了，并且config中的OUTPUT_DIR里并没有新的文件。请问Network Fine-tuning这一步是有什么输出吗？
我觉得这里可能存在一些问题，但是我并不知道问题出在哪里。

**Comment by wuminye** [comment]
Our code terminates training according to the value of  SOLVER.MAX_EPOCHS in config.yml file of the checkpoint .

**Comment by faneggs** [comment]
> Our code terminates training according to the value of SOLVER.MAX_EPOCHS in config.yml file of the checkpoint .

好滴好滴，感谢~！

**Comment by faneggs** [comment]
你好~
请问Network Training和Network Fine-tuning两个过程的epoch的数量你是怎么分配的呢？
