### ISSUE TITLE
Composition of camera intrinsics and extrinsics

### ISSUE THREAD

**Issue by ghost** [wuminye/NHR#6]
Hi,
I wanna train this project on my own dataset, so I wonder how the camera extrinsics are arranged in the file `CamPose.inf`?
I read the file `tools/render.ipynb`, where the cosine of the Angle of rotation about the Z-axis, X-axis, Y-axis are arranged in order in the direction of the column. Is this the correct order of the input camera extrinsics to the training process?
I wonder whether the camera intrinsics in file `Intrinsic.inf`, the number in matrix [0,1] is caused by camera distortion?
And what is the parameter whose name is INPUT.NEAR_FAR_SIZE in the file `config.yml`?

Since my dataset needs to be adjusted in accordance with the format required by the training input, I would like to consult you about these matters. Thank you so much~

**Comment by wuminye** [comment]
1. About camera parameters format：Code at the end of tools/render.ipynb has a part where regular 4x4 extrinsics（camera to world) and 3x3 intrinsics are converted into *.inf files, which you can refer to.
2. The number you mentioned in intrinsic matrix is the axis skew of intrinsic matrix , which causes shear distortions.
3. Our code can automatically compute the near_far of a specific scene according to its point clouds. The item in yml file is duplicated.

**Comment by ghost** [comment]
> 1. About camera parameters format：Code at the end of tools/render.ipynb has a part where regular 4x4 extrinsics（camera to world) and 3x3 intrinsics are converted into *.inf files, which you can refer to.
> 2. The number you mentioned in intrinsic matrix is the axis skew of intrinsic matrix , which causes shear distortions.
> 3. Our code can automatically compute the near_far of a specific scene according to its point clouds. The item in yml file is duplicated.

Thanks for your reply. It's a great help to me.
