### ISSUE TITLE
Missing files in released dataset

### ISSUE THREAD

**Issue by derrick-xwp** [wuminye/NHR#7]
Hi Mr, Wu

The point cloud files and some frames of images are missing in the released dataset.

**Comment by wuminye** [comment]
Hi, 
Could you please specify  in which sequence point cloud files and images are missing?  
Another thing we need to check is the MD5 checksum of 7z files. So could you provide the MD5 checksum value of the files you have downloaded?

**Comment by derrick-xwp** [comment]
Hi Mr. Wu,
I download them again and they are complete now.
But the link for dance dataset is down, so appreciate if you can take a look when you are convenient!
Thanks,

**Comment by KosukeFukazawa** [comment]
+1
