### ISSUE TITLE
Nan

### ISSUE THREAD

**Issue by zxy110** [wuminye/NHR#8]
Hi, 
 
I want to know how the parameter MUL_POINTNET works?
I found the training process will be Nan when I train one dataset with MUL_POINTNET=True, but I found in code it is the same as MUL_POINTNET=False when there is only one dataset.

Looking forward to your reply. Thanks!

Best regards,
Leo

**Comment by wuminye** [comment]
Hi,

You can set MUL_POINTNET to be false if you train networks on only one dataset. 

MUL_POINTNET is designed for multiple datasets training.  If MUL_POINTNET is on, the code will assign each dataset a Pointnet and uses different Pointnets to predict point features according to the indexes of the datasets. 

As for the Nan issue, please check if point clouds and cameras are in the same coordinate system.  This problem might happen when camera parameters and point clouds are mismatched.
